### ISSUE TITLE
Accept a query struct as a selector on Derive.Ecto.Selector

### ISSUE THREAD

**Issue by rwillians** [TurtleAI/derive#22]
`Derive.Ecto.Selector` should accept a `%Query{}` (ideally, any query-able supported by Ecto) as selector.
https://github.com/TurtleAI/derive/blob/master/lib/derive/ecto/selector.ex#L23-L31

A common use case is changing multiple rows with a single query. For example:

```elixir
def handle_event(%InvoiceIssued{} = event) do
  [
    [ids: event.line_item_ids]
    |> Query.invoice_line_items() # returns a %Query{} struct
    |> update(%{status: :invoiced})
  ]
end
```

A possible implementation (in https://github.com/TurtleAI/derive/blob/master/lib/derive/ecto/selector.ex#L23-L31) is:

```elixir
def selector_query(%Query{} = query), do: query
```

Doing multiple operations is likely -- although I didn't measure it -- performance impact.

**Comment by venkatd** [comment]
@rwillians my current preference is to keep selectors as simple as possible.

We do support dropping down to a regular `%Ecto.Query` in cases where we want more complex behaviors.
If there is an Ecto query, Derive assumes it's an update statement and runs it as-is.

For example:
https://github.com/TurtleAI/turtle-api/blob/master/lib/turtle/project/reducer.ex#L96-L122

How we handle `Turtle.Event.CardDeleted` is most similar to what you're trying to accomplish.

LMK if that works. If not can re-open.
